[theme]
primaryColor = "#2E86DE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#495057"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true
enableCORS = false
headless = true

[browser]
gatherUsageStats = false
